baseURL = "https://example.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Fluency"
theme = "fluency"
enableRobotsTXT = true
summaryLength = 100
pygmentsUseClasses = true
pygmentsCodefences = true
hasCJKLanguage = false
enableEmoji = true
ignoreErrors = [ "error-remote-getjson" ]

[minify]
disableSVG = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"

[params]
author = "Hugo Author"
description = "A fluent Hugo theme for writers and bloggers."
mainSections = [ "posts" ]
disableComment = true
disableCommentByType = [ "page" ]
thirdPartyComment = """
this is your comment
"""
mathRender = true

  [params.pageSize]
  index = 5
  list = 10
  archives = 20

[[menu.main]]
identifier = "posts"
name = "posts"
url = "posts/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "tags"
url = "tags/"
weight = 2

[[menu.main]]
identifier = "archives"
name = "archives"
url = "archives/"
weight = 3

[[menu.main]]
identifier = "about"
name = "about"
url = "about/"
weight = 4

[[menu.footer]]
identifier = "twitter"
url = "https://twitter.com/gohugoio"
name = "Twitter"

[[menu.footer]]
identifier = "github"
url = "https://github.com/gohugoio"
name = "Github"

[privacy.disqus]
disable = false

[privacy.googleAnalytics]
anonymizeIP = false
disable = false
respectDoNotTrack = false
useSessionStorage = false

[privacy.instagram]
disable = false
simple = false

[privacy.twitter]
disable = false
enableDNT = false
simple = false

[privacy.vimeo]
disable = false
enableDNT = false
simple = false

[privacy.youtube]
disable = false
privacyEnhanced = false
